/*
Exercise 7: Log the length of a string

Follow the steps. Make sure that each step is written on the line after.

Declare a variable called mySentence and initialize it with the following string: "Programming is so interesting!".
Figure out (using Google) how to get the length of mySentence.
Write a console.log statement to log the length of mySentence.
*/
'use strict';
let mySentence = 'Programming is so interesting!';
let l = mySentence.length;
console.log(l);
